---
title: "Map HPI"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    source_code: embed
    orientation: rows
    vertical_layout: fill
---

```{r setup, include = FALSE}
# Load packages and initialize data here
library(tigris)
library(tidyverse)
library(tidyquant)
library(leaflet)
library(highcharter)
library(Quandl)
library(rgeos)

# You might want to supply an api key
Quandl.api_key("d9EidiiDWoFESfdk5nPy")

states <- states(cb = TRUE, class = "sf")

states_hpi <- 
 Quandl("FMAC/HPI", order = 'asc')

states_wrangled <- 
  states_hpi %>%
  filter(Date == ymd("2016-03-31") | Date == ymd("2017-03-31")) %>%
  gather(state, value, -Date) %>% 
  group_by(state) %>% 
  mutate(hpa = (value - lag(value))/ lag(value)) %>%
  mutate(hpa = round(hpa, digits = 4) * 100)  %>%
  na.omit() %>% 
  select(state, hpa) %>% 
  rename(STUSPS = state)

states_hpa_leaflet <- merge(states, states_wrangled, by = "STUSPS", all.x = TRUE)

statesPal<-colorNumeric(
  palette = "GnBu",
  domain = states_hpa_leaflet$hpa)

statesPopup <- paste0( 
                    states_hpa_leaflet$NAME,
                    "<br>Annual House Price Percent Change: ", 
                     states_hpa_leaflet$hpa, "%")

leaf_states <- 
  leaflet(states_hpa_leaflet) %>% 
  addProviderTiles("CartoDB.Positron") %>%   
  setView(-95, 40, zoom = 4) %>% 
  addPolygons(stroke = TRUE, color = "black", weight = .4, opacity = 1.0, 
              smoothFactor = 0.5, fill = TRUE, fillColor = ~statesPal(hpa), 
              fillOpacity = .8, layerId = ~STUSPS, popup = statesPopup)

```

House Prices by State {data-orientation=rows}
=====================================

Row {data-height=550}
-------------------------------------

### Map shaded by annual houe price appreciation. Click to see HPI over time.

```{r, echo = FALSE}

leafletOutput("map1")

  output$map1 <- renderLeaflet({
   leaf_states
  })

clicked_state<- eventReactive(input$map1_shape_click, {
  return(input$map1_shape_click$id)
})


state_data <- reactive({
  data_set <- paste("FMAC/HPI_", as.character(clicked_state()), sep = "")
  state_data <- Quandl(data_set, type = "xts", order = "asc")
  index(state_data) <- as.Date(as.yearmon(index(state_data), format = '%Y%m'))
  state_data
}) 

```


Row {data-height=450}
-----------------------------------------------------------------------

### HPI over time

```{r}
highchartOutput("highchart")
   
output$highchart <- renderHighchart({

  validate(need(input$map1_shape_click$id != "",
                "Please click on a state to display its HPI price history."))
  
  state_name <- state.name[match(as.character(clicked_state()),state.abb)]
  title <- paste(state_name, "HPI", sep = " ")
  
  highchart(type = "stock") %>% 
    hc_title(text = title) %>%
    hc_add_series(state_data(), name = title)%>% 
    hc_navigator(enabled = FALSE) %>% 
    hc_scrollbar(enabled = FALSE)
})
```



